version: "3.8"
services:
  # Spanner
  spanner:
    platform: linux/amd64
    image: gcr.io/cloud-spanner-emulator/emulator:1.5.14
    ports:
      - "9010:9010"
      - "9020:9020"

  # Init (Create Instance)
  spanner-init:
    platform: linux/amd64
    image: google/cloud-sdk:465.0.0-slim
    command: >
      bash -c 'gcloud config configurations create emulator &&
              gcloud config set project $${PROJECT_ID} &&
              gcloud config set api_endpoint_overrides/spanner $${SPANNER_EMULATOR_URL} &&
              gcloud config set auth/disable_credentials true &&
              gcloud spanner instances create $${INSTANCE_NAME} --config=emulator-config --description=Emulator --nodes=1 &&
              gcloud spanner databases create $${DATABASE_NAME} --instance=$${INSTANCE_NAME}'
    environment:
      PROJECT_ID: "test-project"
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
      INSTANCE_NAME: "test-instance"
      DATABASE_NAME: "test-database"
    depends_on:
      - spanner
